-- Generated by the k4 installer. DO NOT EDIT: updates overwrite this file.
--
-- Everything k4 needs from Hyprland: shortcuts and startup.
--
-- To remove the integration, delete this file and its `require("config.k4")`
-- line in hyprland.lua. During updates the installer may remove old k4 lines
-- from your Hyprland files, keeping a *.k4.bak backup beside each first.
--
-- Watch for conflicts: Hyprland's Lua API ACCUMULATES bindings instead of
-- replacing them as the classic format does for two `bind` lines on one key.
-- Two bindings on one key are TWO live actions, not one overriding the other.
-- On Nix, do not edit this file: `programs.k4.hyprland.template` accepts your
-- own template, leaving this one intact for comparison.

local mod = "SUPER"
local raiz = "@RAIZ@"

-- IPC commands. `k4` is the general target, retained for compatibility;
-- new modules publish their own targets.
local k4 = "quickshell ipc -p " .. raiz .. "/shell.qml call k4 "
local apps = "quickshell ipc -p " .. raiz .. "/shell.qml call k4.apps "
local term = "quickshell ipc -p " .. raiz .. "/shell.qml call k4.term "
local ssh = "quickshell ipc -p " .. raiz .. "/shell.qml call k4.ssh "

----------------------------------------------------------------------------
-- Startup
----------------------------------------------------------------------------
-- `launch` runs instead of plain `quickshell` on purpose: it is what
-- sets QML_IMPORT_PATH so plugins can write `import K4`. Launching
-- quickshell directly the bar does not come up.
hl.on("hyprland.start", function()
    hl.exec_cmd(raiz .. "/launch --no-duplicate -d")
end)

----------------------------------------------------------------------------
-- Island
----------------------------------------------------------------------------
hl.bind(mod .. " + Space",       hl.dsp.exec_cmd(k4 .. "toggleLauncher"))
-- The bar's application drawer: what k4 itself can open.
-- Deliberately beside the launcher: Space launches desktop applications,
-- SHIFT+Space the bar's applications. The original choice, SUPER+D, was
-- already bound to fullscreen in the author's CachyOS configuration.
hl.bind(mod .. " + SHIFT + Space", hl.dsp.exec_cmd(apps .. "toggle"))
hl.bind(mod .. " + I",           hl.dsp.exec_cmd(k4 .. "togglePanel"))
hl.bind(mod .. " + X",           hl.dsp.exec_cmd(k4 .. "togglePanel"))
hl.bind(mod .. " + N",           hl.dsp.exec_cmd(k4 .. "toggleNotifications"))
hl.bind(mod .. " + A",           hl.dsp.exec_cmd(k4 .. "toggleNotifications"))
hl.bind(mod .. " + Z",           hl.dsp.exec_cmd(k4 .. "settings"))
hl.bind(mod .. " + SHIFT + W",   hl.dsp.exec_cmd(k4 .. "settingsSection wallpaper"))
hl.bind(mod .. " + V",           hl.dsp.exec_cmd(k4 .. "clipboard"))
hl.bind(mod .. " + K",           hl.dsp.exec_cmd(k4 .. "keys"))
hl.bind(mod .. " + ALT + C",     hl.dsp.exec_cmd(k4 .. "session"))
----------------------------------------------------------------------------
-- Terminal
----------------------------------------------------------------------------
-- Leave plain SUPER+T alone: it opens the user's usual terminal. The island
-- terminal adds SHIFT: the same letter, with SHIFT selecting k4's terminal.
--
-- These are two presentations of the same session: SHIFT shows it in the
-- island for quick work, while ALT MOVES it into a larger window for longer
-- tasks. Whatever is running inside continues without interruption.
--
-- ALT works both ways: pressed over a k4term window, it returns that session
-- to the island. One gesture for both directions.
hl.bind(mod .. " + SHIFT + T",   hl.dsp.exec_cmd(term .. "island"))
hl.bind(mod .. " + ALT + T",     hl.dsp.exec_cmd(term .. "move"))

-- Reach your servers quickly: open the picker, type a few letters, connect.
-- Hosts come from ~/.ssh/config, so ssh, scp and git share the same entries.
--
-- Use ALT rather than SHIFT: SUPER+SHIFT+S was already the user's shortcut
-- for moving a window to the special workspace, and should not be taken over.
hl.bind(mod .. " + ALT + S",     hl.dsp.exec_cmd(ssh .. "abrir"))

----------------------------------------------------------------------------
-- Assistant
----------------------------------------------------------------------------
-- Selected text is not attached automatically: the header offers it, and Tab,
-- a click on the chip, or the last shortcut below attaches it.
hl.bind(mod .. " + G",           hl.dsp.exec_cmd(k4 .. "ask"))
hl.bind(mod .. " + SHIFT + G",   hl.dsp.exec_cmd(k4 .. "askScreen"))
hl.bind(mod .. " + ALT + G",     hl.dsp.exec_cmd(k4 .. "askRegion"))
hl.bind(mod .. " + CONTROL + G", hl.dsp.exec_cmd(k4 .. "askSelection"))

----------------------------------------------------------------------------
-- Multimedia
----------------------------------------------------------------------------
-- `locked` keeps these shortcuts working while the screen is locked.
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd(k4 .. "togglePlay"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(k4 .. "togglePlay"), { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd(k4 .. "nextTrack"),  { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd(k4 .. "prevTrack"),  { locked = true })

----------------------------------------------------------------------------
-- Clicks
----------------------------------------------------------------------------
