#!/usr/bin/env python3
"""One-way, non-secret adapters for consumers that cannot read config.json."""
import argparse
import json
import os
import re
from pathlib import Path

import config_store as store

TERMINAL_KEYS = {"font": "fuente", "size": "tamaño", "opacity": "opacidad", "trail": "estela",
                 "quiet": "tranquilo", "scrollback": "historial", "ink": "tinta", "background": "fondo"}


def parse_monitor_rules(text):
    outputs = []
    pattern = r'hl\.monitor\(\{ output = ("(?:[^"\\]|\\.)*"), mode = ("(?:[^"\\]|\\.)*"), position = ("[^"]+"), scale = ([\d.]+), transform = (\d+), disabled = (true|false), mirror = ("(?:[^"\\]|\\.)*") \}\)'
    for match in re.finditer(pattern, text):
        name, mode, position, scale, transform, disabled, mirror = match.groups()
        x, y = json.loads(position).split("x")
        outputs.append(dict(name=json.loads(name), mode=json.loads(mode), x=int(x), y=int(y),
                            scale=float(scale), transform=int(transform), enabled=disabled == "false", mirror=json.loads(mirror)))
    if not outputs:
        raise ValueError("Unrecognized historical monitor rules")
    return outputs


def terminal():
    values = store.get(["plugins", "terminal", "settings"], {})
    text = "# Generated by k4. Edit ~/.config/k4/config.json instead.\n"
    for key, value in values.items():
        if key in set(TERMINAL_KEYS) | {"shell", "term"} and "\n" not in str(value):
            if key in ("trail", "quiet") and value == "yes":
                value = "si"
            text += TERMINAL_KEYS.get(key, key) + " = " + str(value) + "\n"
    path = store.config_path().parent.parent / "k4term/k4term.conf"
    if not path.exists() or path.read_text() != text:
        store.atomic_write(path, text)


def monitors():
    from monitors import confirmed_lua
    return confirmed_lua(store.get(["features", "monitors", "outputs"], []))


def monitor_compatibility():
    # An already-installed Home Manager generation may still dofile this
    # path. It is now generated output, never the saved layout's authority.
    if store.get(["features", "monitors", "integration"]) == "lua":
        path = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local/state") / "k4/monitors/confirmed.lua"
        text = monitors()
        if not path.exists() or path.read_text() != text:
            store.atomic_write(path, text)


def ssh():
    # User-owned ~/.ssh/config is only extended with an Include; its existing
    # blocks and comments remain intact. Canonical k4 hosts are structured JSON.
    hosts = store.get(["plugins", "ssh", "hosts"], {})
    directory = Path.home() / ".ssh"
    if not hosts and not (directory / "k4.conf").exists():
        return
    directory.mkdir(mode=0o700, exist_ok=True)
    target = directory / "k4.conf"
    lines = ["# Generated by k4 from the local SSH profile."]
    for alias, fields in hosts.items():
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", alias):
            raise ValueError("Invalid SSH alias")
        lines.append("Host " + alias)
        for key, option in {"host": "HostName", "user": "User", "port": "Port", "identityFile": "IdentityFile", "jumpHost": "ProxyJump", "identitiesOnly": "IdentitiesOnly", "batchMode": "BatchMode"}.items():
            value = str(fields.get(key, ""))
            if value:
                if any(c in value for c in "\n\r\0"):
                    raise ValueError("Invalid SSH value")
                quoted = '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"' if any(c.isspace() or c in '#"' for c in value) else value
                lines.append("    " + option + " " + quoted)
        lines.append("    StrictHostKeyChecking accept-new")
    generated = "\n".join(lines) + "\n"
    if not target.exists() or target.read_text() != generated:
        store.atomic_write(target, generated)
    path = directory / "config"
    text = path.read_text() if path.exists() else ""
    include = "Include ~/.ssh/k4.conf"
    if include not in text.splitlines():
        store.atomic_write(path, include + "\n" + text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("terminal", "monitors", "ssh", "all"))
    action = parser.parse_args().action
    if action == "monitors":
        store.initialize()
        runtime = os.environ.get("XDG_RUNTIME_DIR")
        if runtime:
            store.atomic_write(Path(runtime) / "k4/monitors-managed", "managed\n")
        print(monitors(), end="")
    else:
        if action in ("terminal", "all"):
            terminal()
        if action in ("ssh", "all"):
            ssh()
        if action == "all":
            monitor_compatibility()
